---
servers:
  - url: https://sandbox.api.service.nhs.uk/connecting-party-manager/FHIR/R4
    description: Sandbox environment.
  - url: https://int.api.service.nhs.uk/connecting-party-manager/FHIR/R4
    description: Integration test environment.
  - url: https://api.service.nhs.uk/connecting-party-manager/FHIR/R4
    description: Production environment.
