---
info:
  version: 1.0.0
  title: Connecting Party Manager
  contact:
    name: NHS Digital API Management
    url: "https://digital.nhs.uk/developer/help-and-support"
    email: api.management@nhs.net
  license:
    name: MIT
    url: https://github.com/NHSDigital/connecting-party-manager/blob/main/LICENCE.md
  description: |
    ## Overview

    Use this API to access the Connecting Party Manager (CPM) service - an internal service for registering and managing details of IT systems and applications that connect to our APIs – sometimes known as ‘connecting parties’ and referred to herein as ‘products’.

    Each product is owned by a ‘product team’. Product teams are associated with software development or healthcare organisations, identified by an ODS code.

    You can:
    * create (register) a product team
    * get product team details
    * delete a product team
    * create (register) a product
    * get details of a single product
    * get details of all products for a given product team or organisation
    * delete a product

    ## Who can use this API

    Currently this API is for [internal use only](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#statuses).

    ## API status and roadmap

    This API is in development, meaning:

    * it is available for testing in the integration environment
    * we expect to make breaking changes based on developer feedback

    ## Service level

    This API is a bronze service, meaning it is operational and supported only during business hours (8 am to 6 pm), Monday to Friday excluding bank holidays.

    For more details, see [service levels](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#service-levels).

    ## Technology

    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/our-api-technologies#basic-rest).

    ## Network access

    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network).

    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation

    This API is application-restricted, meaning we authenticate the calling application but not the end user.

    To use this API, use the following security pattern:

    * [Application-restricted RESTful API - signed JWT authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-signed-jwt-authentication)

    ## Errors

    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    * 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    * 400 to 499 if it failed because of a client error by your application
    * 500 to 599 if it failed because of an error on our server

    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#http-status-codes) for more on errors.

    ## Open source

    You might find the following open source resources useful:

    | Resource                       | Description                                | Links                                                                    |
    |--------------------------------|--------------------------------------------|--------------------------------------------------------------------------|
    | Connecting Party Manager       | Source code for the core API and sandbox   | [GitHub repo](https://github.com/NHSDigital/connecting-party-manager)    |
    | Connecting Party Manager - CI  | Source code for the Github Actions runners | [GitHub repo](https://github.com/NHSDigital/connecting-party-manager-CI) |

    We currently don't have any open source client libraries or sample code for this API. If you think this would be useful, you can [upvote the suggestion on our Interactive Product Backlog](https://nhs-digital-api-management.featureupvote.com/suggestions/107439/client-libraries-and-reference-implementations).

    ## Environments and testing

    | Environment       | Base URL                                                                    |
    | ----------------- | --------------------------------------------------------------------------- |
    | Sandbox           | `https://sandbox.api.service.nhs.uk/connecting-party-manager/`      |
    | Integration       | `https://int.api.service.nhs.uk/connecting-party-manager/` |
    | Production        | `https://api.service.nhs.uk/connecting-party-manager/`     |

    ### Sandbox and Integration environments

    Our [sandbox environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#sandbox-testing):

    * is for early developer testing,
    * is open access, so does not allow you to test authorisation,
    * includes ready-to-use test data - for details [contact us](https://digital.nhs.uk/developer/help-and-support),
    * underpins our `Try this API` feature; see the documentation for each endpoint for more details.

    Our [integration test environment](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing):

    * is for formal integration testing,
    * includes authorisation,
    * includes ready-to-use test data - for details [contact us](https://digital.nhs.uk/developer/help-and-support).

    For more details see [integration testing with our RESTful APIs](https://digital.nhs.uk/developer/guides-and-documentation/testing#integration-testing-with-our-restful-apis).

    ## Onboarding

    This API is not yet available for onboarding.

    ## Change log

    For details of how this API has changed over time, see the [change log](https://github.com/NHSDigital/connecting-party-manager/blob/main/CHANGELOG.md).
