---
info:
  version: 1.0.0
  title: Connecting Party Manager - FHIR API
  contact:
    name: NHS Digital API Management
    url: "https://digital.nhs.uk/developer/help-and-support"
    email: api.management@nhs.net
  license:
    name: MIT
    url: https://github.com/NHSDigital/connecting-party-manager/blob/main/LICENCE.md
  description: |
    ## Overview

    TBC
