---
openapi: 3.0.3
x-nhsd-apim:
  access:
    - title: Application Restricted
      grants:
        app-level0: []
  target: # Only one target (omit for NO backend)
    type: external
    healthcheck: /_status
    url: https://i38bu8egci.execute-api.eu-west-2.amazonaws.com/production #for now this is the dev gateway
    security:
      type: apikey
      header: apikey
      secret: rowan-cpm-test-8
  target-attributes:
    - name: nrl-ods-RJ11
      required: true
    - name: nrlf-ods-object.cpm.code
      required: false
    - name: nrlf-ods-object.cpm
      required: true
    - name: nrlf-ods-object
      required: true
    - name: nrlf-ods-array
      required: true
    - name: missing
      required: false
