---
x-nhsd-apim:
  access:
    - title: User Restricted
      grants:
        nhs-login-p5: []
    - title: Application Restricted
      grants:
        app-level0: []
  target: # Only one target (omit for NO backend)
    type: external
    healthcheck: /_status
    url: https://example.external.apikey.secured.backend.com
    security:
      type: apikey
      header: X-API-Key
      secret: example-apikey-secret-name
