---
x-definitions:
  ApiGatewayIntegration:
    type: object
    x-amazon-apigateway-integration: &ApiGatewayIntegration
      type: aws_proxy
      httpMethod: POST
      responses:
        default:
          statusCode: "200"
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT

paths:
  /_status:
    get:
      summary: _status endpoint for APIGEE integration
      operationId: status
      responses:
        "200":
          $ref: "#/components/responses/StatusOK"
        "404":
          $ref: "#/components/responses/NotFound"
      parameters:
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_status}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam:
    post:
      operationId: createproductteam
      summary: createProductTeam endpoint for APIGEE integration
      requestBody:
        $ref: "#/components/requestBodies/ProductTeamCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/ProductTeamCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
      parameters:
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}:
    get:
      operationId: readproductteam
      summary: readProductTeam endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/ProductTeamRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product:
    get:
      operationId: searchCpmProduct
      summary: searchCpmProduct endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/ProductSearch"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []
    post:
      operationId: createproductendpoint
      summary: createProduct endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/ProductCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/ProductCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}:
    get:
      operationId: readproductendpoint
      summary: readProduct endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/ProductRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

    delete:
      operationId: deleteproductendpoint
      summary: deleteProduct endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "204":
          description: Delete Product operation successful
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_deleteCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/Epr:
    post:
      operationId: createproductforeprendpoint
      summary: createCpmProductForEpr endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/ProductCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/EprProductCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createCpmProductForEpr}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}/DeviceReferenceData:
    post:
      operationId: createDeviceReferenceData
      summary: createDeviceReferenceData endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/DeviceReferenceDataCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/DeviceRefDataCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDeviceReferenceData}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  ? /ProductTeam/{product_team_id}/Product/{product_id}/DeviceReferenceData/MhsMessageSet
  : post:
      operationId: createDeviceReferenceDataMessageSet
      summary: createDeviceReferenceDataMessageSet endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - name: product_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                questionnaire_responses:
                  type: object
                  description: Questionnaire Responses for MHS Message Set questionnaire
      responses:
        responses:
        "201":
          <<: *Response201
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDeviceReferenceDataMessageSet}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  ? /ProductTeam/{product_team_id}/Product/{product_id}/DeviceReferenceData/{device_reference_data_id}
  : get:
      operationId: readDeviceReferenceData
      summary: readDeviceReferenceData endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/DeviceReferenceDataId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/DeviceRefDataRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readDeviceReferenceData}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}/Device:
    post:
      operationId: createDevice
      summary: createDevice endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/DeviceCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/DeviceCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}/Device/{device_id}:
    get:
      operationId: readDevice
      summary: readDevice endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/DeviceId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/DeviceRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /searchSdsDevice:
    get:
      operationId: searchsdsdevice
      summary: searchSdsDevice endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/NhsAsClient"
        - $ref: "#/components/parameters/NhsAsClientInteration"
        - $ref: "#/components/parameters/NhsMhsManOrg"
        - $ref: "#/components/parameters/NhsMhsPartyKey"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/SdsDeviceSearch"
        "400":
          $ref: "#/components/responses/BadRequest"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchSdsDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /searchSdsEndpoint:
    get:
      operationId: searchsdsendpoint
      summary: searchSdsEndpoint endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/NhsIdCode"
        - $ref: "#/components/parameters/NhsMhsInteration"
        - $ref: "#/components/parameters/NhsMhsPartyKey"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/SdsEndpointSearch"
        "400":
          $ref: "#/components/responses/BadRequest"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchSdsEndpoint}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /Questionnaire/{questionnaire_id}:
    get:
      operationId: readQuestionnaire
      summary: readQuestionnaire endpoint for APIGEE integration
      parameters:
        - $ref: "#/components/parameters/QuestionnaireId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/QuestionnaireRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readQuestionnaire}
      security:
        - ${authoriser_name}: []
        - app-level0: []
