---
x-definitions:
  ApiGatewayIntegration:
    type: object
    x-amazon-apigateway-integration: &ApiGatewayIntegration
      type: aws_proxy
      httpMethod: POST
      responses:
        default:
          statusCode: "200"
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT

  RequestHeaders:
    - &RequestHeaderVersion
      in: header
      name: version
      schema:
        $ref: "#/components/schemas/Version"
    - &RequestHeaderRequestId
      in: header
      name: x-request-id
      schema:
        $ref: "#/components/schemas/RequestId"
    - &RequestHeaderCorrelationId
      in: header
      name: x-correlation-id
      schema:
        $ref: "#/components/schemas/CorrelationId"
    - headers: &RequestHeaders
        parameters:
          - *RequestHeaderVersion
          - *RequestHeaderRequestId
          - *RequestHeaderCorrelationId

  ErrorResponses:
    "4XX": &Response4XX
      description: "Client Error"
      content:
        application/fhir+json:
          schema:
            $ref: "#/components/schemas/OperationOutcome"

paths:
  /_status:
    get:
      summary: _status endpoint for APIGEE integration
      operationId: status
      responses:
        "200":
          $ref: "#/components/responses/StatusOK"
        "4XX":
          <<: *Response4XX
      <<: *RequestHeaders
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_status}

  /Organization:
    post:
      responses:
        "4XX":
          <<: *Response4XX
      <<: *RequestHeaders
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createProductTeam}

  /Organization/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readProductTeam}
