---
x-definitions:
  ApiGatewayIntegration:
    type: object
    x-amazon-apigateway-integration: &ApiGatewayIntegration
      type: aws_proxy
      httpMethod: POST
      responses:
        default:
          statusCode: "200"
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT

  RequestHeaders:
    - &RequestHeaderVersion
      in: header
      name: version
      schema:
        $ref: "#/components/schemas/Version"
    - &RequestHeaderRequestId
      in: header
      name: x-request-id
      schema:
        $ref: "#/components/schemas/RequestId"
    - &RequestHeaderCorrelationId
      in: header
      name: x-correlation-id
      schema:
        $ref: "#/components/schemas/CorrelationId"
    - headers: &RequestHeaders
        parameters:
          - *RequestHeaderVersion
          - *RequestHeaderRequestId
          - *RequestHeaderCorrelationId

  SuccessResponses:
    "201": &Response201
      description: Create operation successful
      content:
        application/fhir+json:
          schema:
            $ref: "#/components/schemas/OperationOutcome"

  ErrorResponses:
    "4XX": &Response4XX
      description: "Client Error"
      content:
        application/fhir+json:
          schema:
            $ref: "#/components/schemas/OperationOutcome"

paths:
  /_status:
    get:
      summary: _status endpoint for APIGEE integration
      operationId: status
      responses:
        "200":
          $ref: "#/components/responses/StatusOK"
        "4XX":
          <<: *Response4XX
      <<: *RequestHeaders
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_status}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /Organization:
    post:
      responses:
        "201":
          <<: *Response201
        "4XX":
          <<: *Response4XX
      <<: *RequestHeaders
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /Organization/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam:
    post:
      operationId: createproductteam
      summary: createProductTeam endpoint for APIGEE integration
      requestBody:
        $ref: "#/components/requestBodies/Organization"
      responses:
        "201":
          <<: *Response201
        "4XX":
          <<: *Response4XX
      <<: *RequestHeaders
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}:
    get:
      operationId: readproductteam
      summary: readProductTeam endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - $ref: "#/components/parameters/profileParam"
        - $ref: "#/components/parameters/lastUpdatedParam"
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/securityParam"
        - $ref: "#/components/parameters/sourceParam"
        - $ref: "#/components/parameters/idParam"
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "200":
          description: Read Product Team operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Organization"
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product:
    get:
      operationId: searchCpmProduct
      summary: searchCpmProduct endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - $ref: "#/components/parameters/profileParam"
        - $ref: "#/components/parameters/lastUpdatedParam"
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/securityParam"
        - $ref: "#/components/parameters/sourceParam"
        - $ref: "#/components/parameters/idParam"
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "200":
          description: Search CpmProducts operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []
    post:
      operationId: createproductendpoint
      summary: createProduct endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                  description: Name of the product
      responses:
        "201":
          <<: *Response201
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}:
    get:
      operationId: readproductendpoint
      summary: readProduct endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - name: product_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        responses:
        "200":
          description: Read Product operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

    delete:
      operationId: deleteproductendpoint
      summary: deleteProduct endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - name: product_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        responses:
        "204":
          description: Delete Product operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_deleteCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/Epr:
    post:
      operationId: createproductforeprendpoint
      summary: createCpmProductForEpr endpoint for APIGEE integration
      parameters:
        - name: product_team_id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_name:
                  type: string
                  description: Name of the product
      responses:
        "201":
          <<: *Response201
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createCpmProductForEpr}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /Device:
    post:
      responses:
        "201":
          <<: *Response201
        "4XX":
          <<: *Response4XX
      <<: *RequestHeaders
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []
    get:
      parameters:
        - name: device_type
          in: query
          required: true
          description: "Type of device (product or endpoint)"
          schema:
            type: string
            enum:
              - product
              - endpoint
        - $ref: "#/components/parameters/profileParam"
        - $ref: "#/components/parameters/lastUpdatedParam"
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/securityParam"
        - $ref: "#/components/parameters/sourceParam"
        - $ref: "#/components/parameters/idParam"
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /Device/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          description: logical identifier
          schema:
            type: string
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /searchSdsDevice:
    get:
      operationId: searchsdsdevice
      summary: searchSdsDevice endpoint for APIGEE integration
      parameters:
        - name: nhs_as_client
          in: query
          required: false
          description: "Accredited System Client"
          schema:
            type: string
        - name: nhs_as_svc_ia
          in: query
          required: false
          description: "Accredited System Client Interaction"
          schema:
            type: string
        - name: nhs_mhs_manufacturer_org
          in: query
          required: false
          description: "Manufacturer Organisation"
          schema:
            type: string
        - name: nhs_mhs_party_key
          in: query
          required: false
          description: "Party Key"
          schema:
            type: string
        - $ref: "#/components/parameters/profileParam"
        - $ref: "#/components/parameters/lastUpdatedParam"
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/securityParam"
        - $ref: "#/components/parameters/sourceParam"
        - $ref: "#/components/parameters/idParam"
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "200":
          description: Search Device operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchSdsDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /searchSdsEndpoint:
    get:
      operationId: searchsdsendpoint
      summary: searchSdsEndpoint endpoint for APIGEE integration
      parameters:
        - name: nhs_id_code
          in: query
          required: false
          description: "NHS ID Code"
          schema:
            type: string
        - name: nhs_mhs_svc_ia
          in: query
          required: false
          description: "Endpoint Interaction"
          schema:
            type: string
        - name: nhs_mhs_party_key
          in: query
          required: false
          description: "Party Key"
          schema:
            type: string
        - $ref: "#/components/parameters/profileParam"
        - $ref: "#/components/parameters/lastUpdatedParam"
        - $ref: "#/components/parameters/tagParam"
        - $ref: "#/components/parameters/securityParam"
        - $ref: "#/components/parameters/sourceParam"
        - $ref: "#/components/parameters/idParam"
        - *RequestHeaderVersion
        - *RequestHeaderRequestId
        - *RequestHeaderCorrelationId
      responses:
        "200":
          description: Search Device operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Bundle"
        "4XX":
          <<: *Response4XX
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchSdsEndpoint}
      security:
        - ${authoriser_name}: []
        - app-level0: []
