---
x-definitions:
  # "x-" before "definitions" prevents it from being parsed as an OpenAPI Schema object
  ApiGatewayIntegration:
    type: object
    x-amazon-apigateway-integration: &ApiGatewayIntegration
      type: aws_proxy
      httpMethod: POST
      responses:
        default:
          statusCode: "200"
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT

paths:
  /_status:
    get:
      summary: _status endpoint for APIGEE integration
      operationId: status
      responses:
        "200":
          description: API is operational
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum: ["OK"]
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_status}
  /Organization:
    get:
      tags:
        - Organization
      summary: Read a ProductTeam (FHIR Organization) resource
      operationId: readProductTeam
      responses:
        "201":
          description: Successful read of ProductTeam
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/Organization"
          headers:
            X-Correlation-Id:
              $ref: "#/components/headers/CorrelationId"
            X-Request-Id:
              $ref: "#/components/headers/RequestId"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readProductTeam}
    post:
      tags:
        - Organization
      summary: Create a ProductTeam (FHIR Organization) resource
      operationId: createProductTeam
      responses:
        "201":
          description: Create ProductTeam operation successful
          content:
            application/fhir+json:
              schema:
                $ref: "#/components/schemas/OperationOutcome"
      requestBody:
        $ref: "#/components/requestBodies/Organization"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createProductTeam}
