---
x-definitions:
  ApiGatewayIntegration:
    type: object
    x-amazon-apigateway-integration: &ApiGatewayIntegration
      type: aws_proxy
      httpMethod: POST
      responses:
        default:
          statusCode: "200"
      passthroughBehavior: when_no_match
      contentHandling: CONVERT_TO_TEXT

paths:
  /_status:
    get:
      summary: Retrieve the current Status (GET)
      operationId: status
      responses:
        "200":
          $ref: "#/components/responses/StatusOK"
        "404":
          $ref: "#/components/responses/NotFound"
      parameters:
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_status}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam:
    post:
      operationId: createproductteam
      summary: Create a Product Team resource (POST)
      requestBody:
        $ref: "#/components/requestBodies/ProductTeamCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/ProductTeamCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "422":
          $ref: "#/components/responses/UnprocessableContent"
      parameters:
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}:
    get:
      operationId: readproductteam
      summary: Read a Product Team resource (GET)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/ProductTeamRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readProductTeam}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product:
    get:
      operationId: searchCpmProduct
      summary: Retrieve all Products associated with a Product Team (GET)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/ProductSearch"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []
    post:
      operationId: createproductendpoint
      summary: Create a Product resource (POST)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/ProductCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/ProductCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}:
    get:
      operationId: readproductendpoint
      summary: Read a Product resource (GET)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/ProductRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

    delete:
      operationId: deleteproductendpoint
      summary: Delete a Product resource (DELETE)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "204":
          description: Delete Product operation successful
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_deleteCpmProduct}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/Epr:
    post:
      operationId: createproductforeprendpoint
      summary: Create an EPR Product resource (POST)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/ProductCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/EprProductCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createCpmProductForEpr}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}/DeviceReferenceData:
    post:
      operationId: createDeviceReferenceData
      summary: Create a Device Reference Data resource (POST)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/DeviceReferenceDataCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/DeviceRefDataCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDeviceReferenceData}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  ? /ProductTeam/{product_team_id}/Product/{product_id}/DeviceReferenceData/MhsMessageSet
  : post:
      operationId: createDeviceReferenceDataMessageSet
      summary: Create a Device Reference Data Message Set resource (POST)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/DeviceReferenceDataMessageSetCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/DeviceRefDataCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDeviceReferenceDataMessageSet}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  ? /ProductTeam/{product_team_id}/Product/{product_id}/DeviceReferenceData/{device_reference_data_id}
  : get:
      operationId: readDeviceReferenceData
      summary: Read a Device Reference Data resource (GET)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/DeviceReferenceDataId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/DeviceRefDataRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readDeviceReferenceData}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}/Device:
    post:
      operationId: createDevice
      summary: Create a Device resource (POST)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      requestBody:
        $ref: "#/components/requestBodies/DeviceCreateRequestBody"
      responses:
        "201":
          $ref: "#/components/responses/DeviceCreate"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_createDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /ProductTeam/{product_team_id}/Product/{product_id}/Device/{device_id}:
    get:
      operationId: readDevice
      summary: Read a Device resource (GET)
      parameters:
        - $ref: "#/components/parameters/ProductTeamId"
        - $ref: "#/components/parameters/ProductId"
        - $ref: "#/components/parameters/DeviceId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/DeviceRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /searchSdsDevice:
    get:
      operationId: searchsdsdevice
      summary: Retrieve Device resources for SDS FHIR API (GET)
      parameters:
        - $ref: "#/components/parameters/NhsAsClient"
        - $ref: "#/components/parameters/NhsAsClientInteration"
        - $ref: "#/components/parameters/NhsMhsManOrg"
        - $ref: "#/components/parameters/NhsMhsPartyKey"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/SdsDeviceSearch"
        "400":
          $ref: "#/components/responses/SdsSearchDeviceBadRequest"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchSdsDevice}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /searchSdsEndpoint:
    get:
      operationId: searchsdsendpoint
      summary: Retrieve Endpoint resources for SDS FHIR API (GET)
      parameters:
        - $ref: "#/components/parameters/NhsIdCode"
        - $ref: "#/components/parameters/NhsMhsInteration"
        - $ref: "#/components/parameters/NhsMhsPartyKey"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/SdsEndpointSearch"
        "400":
          $ref: "#/components/responses/SdsSearchEndpointBadRequest"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_searchSdsEndpoint}
      security:
        - ${authoriser_name}: []
        - app-level0: []

  /Questionnaire/{questionnaire_id}:
    get:
      operationId: readQuestionnaire
      summary: Read a Questionnaire resource (GET)
      parameters:
        - $ref: "#/components/parameters/QuestionnaireId"
        - $ref: "#/components/parameters/HeaderVersion"
        - $ref: "#/components/parameters/HeaderRequestId"
        - $ref: "#/components/parameters/HeaderCorrelationId"
      responses:
        "200":
          $ref: "#/components/responses/QuestionnaireRead"
        "404":
          $ref: "#/components/responses/NotFound"
      x-amazon-apigateway-integration:
        <<: *ApiGatewayIntegration
        uri: ${method_readQuestionnaire}
      security:
        - ${authoriser_name}: []
        - app-level0: []
