---
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    StatusOK:
      type: string
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "OK"
        message: "Transaction successful"
    CPMProductTeamResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        ods_code:
          type: string
        status:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
      example:
        id: "a9a9694d-001b-45ce-9f2a-6c9bf80ae0d0"
        name: "Sample Product Team"
        ods_code: "F5H1R"
        status: "active"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "2024-10-15T10:00:00Z"
        deleted_on: "null"
        keys:
          - key_type: "product_team_id_alias"
            key_value: "FOOBAR"
    EPRProductTeamResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        ods_code:
          type: string
        status:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
      example:
        id: "F5H1R.a9a9694d-001b-45ce-9f2a-6c9bf80ae0d0"
        name: "Sample Product Team"
        ods_code: "F5H1R"
        status: "active"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "2024-10-15T10:00:00Z"
        deleted_on: "null"
        keys:
          - key_type: "product_team_id_alias"
            key_value: "FOOBAR"
    ProductResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
      example:
        id: "123-XXX"
        name: "Sample Product Team"
        product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
        ods_code: "F5H1R"
        status: "active"
        keys:
          - key_type: "foo"
            key_value: "bar"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "2024-10-15T10:00:00Z"
        deleted_on: "null"

    Questionnaire:
      type: object
      properties:
        tbc:
          type: string

    ProductSearchResponse:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: "#/components/schemas/ProductResponse"
      example:
        results:
          - id: "123-XXX"
            name: "Sample Product Team"
            product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
            ods_code: "F5H1R"
            status: "active"
            keys:
              - key_type: "foo"
                key_value: "bar"
            created_on: "2024-10-15T10:00:00Z"
            updated_on: "2024-10-15T10:00:00Z"
            deleted_on: "null"

    DeviceResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        environment:
          type: string
        product_id:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
        questionnaire_responses:
          type: object
      example:
        id: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
        name: "Sample Device"
        status: "active"
        environment: "prod"
        product_id: "123-XXX"
        product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
        ods_code: "F5H1R"
        questionnaire_responses:
          - key_type: "foo"
            key_value: "bar"
        created_on: "2025-10-15T10:00:00Z"
        updated_on: "null"
        deleted_on: "null"

    AsDeviceResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_id:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        environment:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        questionnaire_responses:
          type: object

    MhsDeviceResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_id:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        environment:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
        questionnaire_responses:
          type: object

    DeviceSearchResponse:
      type: array
      items:
        $ref: "#/components/schemas/DeviceResponse"

    DeviceReferenceDataResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_id:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        environment:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        questionnaire_responses:
          type: object
      example:
        id: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
        name: "Sample DeviceReferenceDataResponse"
        status: "active"
        environment: "prod"
        product_id: "123-XXX"
        product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
        ods_code: "F5H1R"
        questionnaire_responses:
          - key_type: "foo"
            key_value: "bar"
        created_on: "2025-10-15T10:00:00Z"
        updated_on: "null"
        deleted_on: "null"

    DeviceRefDataSearchResponse:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: "#/components/schemas/DeviceReferenceDataResponse"
      example:
        results:
          - id: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
            name: "Sample Device Reference Data"
            status: "active"
            environment: "prod"
            product_id: "123-XXX"
            product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
            ods_code: "F5H1R"
            questionnaire_responses:
              - key_type: "foo"
                key_value: "bar"
            created_on: "2024-10-15T10:00:00Z"
            updated_on: "null"
            deleted_on: "null"
