---
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    OdsOrganisation:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    ProductTeam:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        organisation:
          $ref: "#/components/schemas/OdsOrganisation"
        owner:
          $ref: "#/components/schemas/User"
