---
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    StatusOK:
      type: string
      properties:
        message:
          type: string
    ProductTeamResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        ods_code:
          type: string
        status:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
        deleted_on:
          type: string
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
      example:
        id: "F5H1R"
        name: "Sample Product Team"
        ods_code: "F5H1R"
        status: "active"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "2024-10-15T10:00:00Z"
        deleted_on: "null"
        keys:
          - key_type: "product_team_id_alias"
            key_value: "FOOBAR"
    ProductResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
        created_on:
          type: string
        updated_on:
          type: string
        deleted_on:
          type: string
      example:
        id: "123-XXX"
        name: "Sample Product Team"
        product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
        ods_code: "F5H1R"
        status: "active"
        keys:
          - key_type: "foo"
            key_value: "bar"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "2024-10-15T10:00:00Z"
        deleted_on: "null"

    Questionnaire:
      type: object
      properties:
        tbc:
          type: string

    ProductSearchResponse:
      type: object
      properties:
        result:
          type: array
          items:
            $ref: "#/components/schemas/ProductResponse"
      example:
        result:
          - id: "123-XXX"
            name: "Sample Product Team"
            product_team_id: "F5H1R.55e86121-3826-468c-a6f0-dd0f1fbc0259"
            ods_code: "F5H1R"
            status: "active"
            keys:
              - key_type: "foo"
                key_value: "bar"
            created_on: "2024-10-15T10:00:00Z"
            updated_on: "2024-10-15T10:00:00Z"
            deleted_on: "null"

    DeviceResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
        product_id:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
        deleted_on:
          type: string
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
        questionnaire_responses:
          type: object
          properties:

    DeviceSearchResponse:
      type: array
      items:
        $ref: "#/components/schemas/DeviceResponse"
    DeviceReferenceDataResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_id:
          type: string
        product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
        deleted_on:
          type: string
    # DeviceReferenceDataMessageSetResponse:
    #   type: object
    #   properties:
    #     id:
    #       type: string
    #     name:
    #       type: string
    #     product_id:
    #       type: string
    #     product_team_id:
    #       type: string
    #     ods_code:
    #       type: string
    #     created_on:
    #       type: string
    #     updated_on:
    #       type: string
    #     deleted_on:
    #       type: string
    #     questionnaire_responses:
    #       type: object
    #       properties:
    #         spine_mhs_message_sets:
    #           type: array
