---
components:
  schemas:
    Device:
      type: object
      discriminator:
        propertyName: resourceType
      properties:
        id:
          type: string
          pattern: '[A-Za-z0-9\-\.]{1,64}'
          description: The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
    OperationOutcome:
      type: object
      properties:
        resourceType:
          type: string
          enum:
            - OperationOutcome
        id:
          type: string
          pattern: "[A-Za-z0-9\\-\\.]{1,64}"
          description: The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
