---
components:
  schemas:
    Empty:
      type: "object"
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
    StatusOK:
      type: string
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "OK"
        message: "Transaction successful"
    CPMProductTeamResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        ods_code:
          type: string
        status:
          type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
      example:
        id: "a9a9694d-001b-45ce-9f2a-6c9bf80ae0d0"
        name: "Sample Product Team"
        ods_code: "F5H1R"
        status: "active"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "null"
        deleted_on: "null"
        keys:
          - key_type: "product_team_id"
            key_value: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
    CPMProductTeamDeleteResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "RESOURCE_DELETED"
        message: "a9a9694d-001b-45ce-9f2a-6c9bf80ae0d0 has been deleted."
    CPMProductResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        product_team_id:
          type: string
        cpm_product_team_id:
          type: string
        ods_code:
          type: string
        status:
          type: string
        keys:
          type: array
          items:
            type: object
            properties:
              key_type:
                type: string
              key_value:
                type: string
        created_on:
          type: string
        updated_on:
          type: string
          nullable: true
        deleted_on:
          type: string
          nullable: true
      example:
        id: "P.1X3-XXX"
        name: "Sample Product"
        product_team_id: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
        cpm_product_team_id: "a9a9694d-001b-45ce-9f2a-6c9bf80ae0d0"
        ods_code: "F5H1R"
        keys: []
        status: "active"
        created_on: "2024-10-15T10:00:00Z"
        updated_on: "null"
        deleted_on: "null"
    CPMProductDeleteResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      example:
        code: "RESOURCE_DELETED"
        message: "P.XYZ-123 has been deleted."
    ProductSearchResponse:
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              org_code:
                type: string
              product_teams:
                type: array
                items:
                  type: object
                  properties:
                    cpm_product_team_id:
                      type: string
                    product_team_id:
                      type: string
                    products:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          name:
                            type: string
                          product_team_id:
                            type: string
                          ods_code:
                            type: string
                          status:
                            type: string
                          keys:
                            type: array
                            items:
                              type: object
                              properties:
                                key_type:
                                  type: string
                                key_value:
                                  type: string
                          created_on:
                            type: string
                          updated_on:
                            type: string
                            nullable: true
                          deleted_on:
                            type: string
                            nullable: true
      example:
        results:
          - org_code: "F5H1R"
            product_teams:
              - product_team_id: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
                cpm_product_team_id: "a9a9694d-001b-45ce-9f2a-6c9bf80ae0d0"
                products:
                  - id: "P.1X3-XYZ"
                    product_team_id: "55e86121-3826-468c-a6f0-dd0f1fbc0259"
                    name: "My Great Product 1"
                    ods_code: "F5H1R"
                    status: "active"
                    created_on: "2024-10-15T10:00:00Z"
                    updated_on: "null"
                    deleted_on: "null"
                    keys: []
              - product_team_id: "24ac1857-f718-4905-813f-52da930c3ea1"
                cpm_product_team_id: "152705aa-0342-487f-a654-64bba814a847"
                products:
                  - id: "P.4Y6-ABC"
                    product_team_id: "24ac1857-f718-4905-813f-52da930c3ea1"
                    name: "My Great Product 3"
                    ods_code: "F5H1R"
                    status: "active"
                    created_on: "2024-10-15T10:00:00Z"
                    updated_on: "null"
                    deleted_on: "null"
                    keys: []
