---
# Request body content and parameter definition
components:
  requestBodies:
    ProductTeam:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductTeam"
      required: true
