---
# Request body content and parameter definition
components:
  requestBodies:
    Device:
      content:
        application/fhir+json:
          schema:
            $ref: "#/components/requestBodies/Device"
      required: true
