---
# Request body content and parameter definition
components:
  requestBodies:
    Organization:
      content:
        application/fhir+json:
          schema:
            $ref: "#/components/schemas/Organization"
      required: true
