---
# Request body content and parameter definition
components:
  requestBodies:
    Organisation:
      content:
        application/fhir+json:
          schema:
            $ref: "#/components/schemas/Organisation"
      required: true
