---
x-definitions:
  ResponseHeaders:
    type: object
    headers: &ResponseHeaders
      X-Correlation-Id:
        schema:
          $ref: "#/components/schemas/HeaderCorrelationId"
      X-Request-Id:
        schema:
          $ref: "#/components/schemas/HeaderRequestId"

components:
  responses:
    StatusOK:
      description: API is operational
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatusOK"
      headers:
        <<: *ResponseHeaders
    NotFound:
      description: Not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              - code: "RESOURCE_NOT_FOUND"
                message: "Could not find <ENTITY> for key ('<ID>')"
    BadRequest:
      description: Bad request (multiple error types)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            MissingValue:
              value:
                errors:
                  - code: "MISSING_VALUE"
                    message: "<MISSING_FIELD>: field required"
            ValidationError:
              value:
                errors:
                  - code: "VALIDATION_ERROR"
                    message: "Item already exists"
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              - code: "UNPROCESSABLE_ENTITY"
                message: "Invalid ODS Code: could not resolve 'https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations/invalid_ods_code'"
    ProductTeamCreate:
      description: Create ProductTeam operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductTeamResponse"
    ProductTeamRead:
      description: Read ProductTeam operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductTeamResponse"
    ProductSearch:
      description: Search Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductSearchResponse"
    ProductCreate:
      description: Create Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductResponse"
    ProductRead:
      description: Read Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductResponse"
    EprProductCreate:
      description: Create Epr Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductResponse"
    DeviceRefDataCreate:
      description: Create Device Reference Data operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceReferenceDataResponse"
    DeviceRefDataRead:
      description: Read Device Reference Data operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceReferenceDataResponse"
    DeviceCreate:
      description: Create Device operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceResponse"
    DeviceRead:
      description: Read Device operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceResponse"
    SdsDeviceSearch:
      description: Search Device operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceSearchResponse"
    SdsEndpointSearch:
      description: Search Endpoint operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/DeviceSearchResponse"
    QuestionnaireRead:
      description: Read Questionnaire operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Questionnaire"
