---
x-definitions:
  ResponseHeaders:
    type: object
    headers: &ResponseHeaders
      X-Correlation-Id:
        schema:
          $ref: "#/components/schemas/CorrelationId"
      X-Request-Id:
        schema:
          $ref: "#/components/schemas/RequestId"

components:
  responses:
    StatusOK:
      description: API is operational
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                enum: ["OK"]
      headers:
        <<: *ResponseHeaders
