---
x-definitions:
  ResponseHeaders:
    type: object
    headers: &ResponseHeaders
      X-Correlation-Id:
        $ref: "#/components/headers/CorrelationId"
      X-Request-Id:
        $ref: "#/components/headers/RequestId"

  OperationOutcome:
    type: object
    context: &OperationOutcome
      application/json:
        schema:
          $ref: "#/components/schemas/OperationOutcome"

components:
  responses:
    CreatedSuccessfully:
      description: Created successfully
      content:
        <<: *OperationOutcome
      headers:
        <<: *ResponseHeaders
    BadRequest:
      description: Bad request
      content:
        <<: *OperationOutcome
      headers:
        <<: *ResponseHeaders
    ProductTeam:
      description: Successfully read a Product Team
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductTeam"
      headers:
        <<: *ResponseHeaders
    NotFound:
      description: Cannot find a Product Team
      content:
        <<: *OperationOutcome
      headers:
        <<: *ResponseHeaders
