---
x-definitions:
  ResponseHeaders:
    type: object
    headers: &ResponseHeaders
      X-Correlation-Id:
        schema:
          $ref: "#/components/schemas/HeaderCorrelationId"
      X-Request-Id:
        schema:
          $ref: "#/components/schemas/HeaderRequestId"

components:
  responses:
    StatusOK:
      description: API is operational
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/StatusOK"
      headers:
        <<: *ResponseHeaders
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              - code: "RESOURCE_NOT_FOUND"
                message: "Could not find <ENTITY> for key ('<ID>')"
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              - code: "CONFLICT"
                message: "Product Team cannot be deleted as it still has associated Product Ids ['P.123-XYZ', 'P.456-ABC']"
    BadRequest:
      description: Bad request (multiple error types)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            MissingValue:
              value:
                errors:
                  - code: "MISSING_VALUE"
                    message: "<MISSING_FIELD>: field required"
                  - code: "MISSING_VALUE"
                    message: "Failed to validate data against '<QUESTIONNAIRE>': '<MISSING_FIELD>' is a required property"
            ValidationError:
              value:
                errors:
                  - code: "VALIDATION_ERROR"
                    message: "Item already exists"
    SearchProductBadRequest:
      description: searchProduct Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          examples:
            ValidationError:
              value:
                errors:
                  - code: "VALIDATION_ERROR"
                    message: "SearchProductQueryParams.__root__: Please provide exactly one valid query parameter: {'product_team_id', 'organisation_code'}."
      headers:
        Access-Control-Allow-Origin:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            errors:
              - code: "UNPROCESSABLE_ENTITY"
                message: "Invalid ODS Code: could not resolve 'https://directory.spineservices.nhs.uk/ORD/2-0-0/organisations/invalid_ods_code'"
    CPMProductTeamCreate:
      description: Create ProductTeam operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CPMProductTeamResponse"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
          example: "*"
    CPMProductTeamRead:
      description: Read ProductTeam operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CPMProductTeamResponse"
    CpmProductTeamDelete:
      description: Delete Product Team operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CPMProductTeamDeleteResponse"
    ProductCreate:
      description: Create Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CPMProductResponse"
      headers:
        Access-Control-Allow-Origin:
          schema:
            type: string
          example: "*"
    ProductRead:
      description: Read Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CPMProductResponse"
    ProductDelete:
      description: Delete Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CPMProductDeleteResponse"
    ProductSearch:
      description: Search Product operation successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductSearchResponse"
