---
components:
  parameters:
    ProductTeamIdQuery:
      name: product_team_id
      in: query
      required: false
      description: Product team identifier to filter results by. Either the "internally" generated id (cpm_product_team_id) or the provided team id (product_team_id)
      schema:
        type: string
    OrganisationCodeQuery:
      name: organisation_code
      in: query
      required: false
      description: The organisation code to filter results by.
      schema:
        type: string
