.PHONY: apigee--deploy apigee--delete apigee--clean apigee--attach-product apigee--detach-product

APIGEE_CONFIG_PATH = $(CURDIR)/infrastructure/apigee
APIGEE_TIMESTAMP = $(TIMESTAMP_DIR)/.apigee.stamp
PROXYGEN_TIMESTAMP = $(TIMESTAMP_DIR)/.proxygen.stamp

SWAGGER_APIGEE = $(SWAGGER_DIST)/apigee/swagger.yaml
WORKSPACE_OUTPUT_JSON = $(CURDIR)/infrastructure/terraform/per_workspace/output.json
ENVIRONMENT_MAPPING_YAML = $(CURDIR)/infrastructure/apigee/environment_mapping.yaml
STAGE_MAPPING_YAML = $(CURDIR)/infrastructure/apigee/stage_mapping.yaml

apigee--deploy: $(PROXYGEN_TIMESTAMP)


apigee--delete: aws--login
	WORKSPACE_OUTPUT_JSON=$(WORKSPACE_OUTPUT_JSON) \
	ENVIRONMENT_MAPPING_YAML=$(ENVIRONMENT_MAPPING_YAML) \
	STAGE_MAPPING_YAML=$(STAGE_MAPPING_YAML) \
	APIGEE_CONFIG_PATH=$(APIGEE_CONFIG_PATH) \
	SWAGGER_APIGEE=$(SWAGGER_APIGEE) \
	AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN) \
		bash $(PATH_TO_INFRASTRUCTURE)/apigee/proxygen.sh delete_proxy $(DEV_BUILD)

apigee--clean:
	[[ -f $(PROXYGEN_TIMESTAMP) ]] && rm $(PROXYGEN_TIMESTAMP) || :

apigee--attach-product: aws--login
	WORKSPACE_OUTPUT_JSON=$(WORKSPACE_OUTPUT_JSON) \
	ENVIRONMENT_MAPPING_YAML=$(ENVIRONMENT_MAPPING_YAML) \
	STAGE_MAPPING_YAML=$(STAGE_MAPPING_YAML) \
	APIGEE_CONFIG_PATH=$(APIGEE_CONFIG_PATH) \
	AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN) \
		bash $(PATH_TO_INFRASTRUCTURE)/apigee/apigee.sh attach_product $(DEV_BUILD)

apigee--detach-product: aws--login
	WORKSPACE_OUTPUT_JSON=$(WORKSPACE_OUTPUT_JSON) \
	ENVIRONMENT_MAPPING_YAML=$(ENVIRONMENT_MAPPING_YAML) \
	STAGE_MAPPING_YAML=$(STAGE_MAPPING_YAML) \
	APIGEE_CONFIG_PATH=$(APIGEE_CONFIG_PATH) \
	AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN) \
		bash $(PATH_TO_INFRASTRUCTURE)/apigee/apigee.sh detach_product $(DEV_BUILD)

$(PROXYGEN_TIMESTAMP): aws--login $(SWAGGER_APIGEE) $(WORKSPACE_OUTPUT_JSON)
	[[ -f $(PROXYGEN_TIMESTAMP) ]] && rm $(PROXYGEN_TIMESTAMP) || :

	WORKSPACE_OUTPUT_JSON=$(WORKSPACE_OUTPUT_JSON) \
	ENVIRONMENT_MAPPING_YAML=$(ENVIRONMENT_MAPPING_YAML) \
	STAGE_MAPPING_YAML=$(STAGE_MAPPING_YAML) \
	APIGEE_CONFIG_PATH=$(APIGEE_CONFIG_PATH) \
	SWAGGER_APIGEE=$(SWAGGER_APIGEE) \
	AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN) \
		bash $(PATH_TO_INFRASTRUCTURE)/apigee/proxygen.sh generate_proxy $(DEV_BUILD)

	touch $(PROXYGEN_TIMESTAMP)
