name: "terraform"
description: "Run terraform commands via the Makefile"
inputs:
  command:
    description: "Terraform command to run"
    required: true
  account:
    description: "AWS account name"
    required: true
  workspace:
    description: "Terraform workspace name"
    required: true
  scope:
    description: "Terraform scope"
    required: true
    default: "per_workspace"
  cache-suffix:
    description: "[Optional] Cache suffix (e.g. 'base')"
    required: false
    default: ""
  restore-from-cache:
    description: "[Optional] restore from cache?"
    required: false
    default: "true"
  save-to-cache:
    description: "[Optional] save to cache?"
    required: false
    default: "false"
  parameter-deploy:
    description: "If account wide parameter deploy then specify 'parameter_deploy'"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/make/
      with:
        command: terraform--${{ inputs.command }} AWS_ACCOUNT="${{ inputs.account }}" TERRAFORM_WORKSPACE="${{ inputs.workspace }}" TERRAFORM_SCOPE="${{ inputs.scope }}"
        requires-aws: true
        restore-from-cache: ${{ inputs.restore-from-cache }}
        save-to-cache: ${{ inputs.save-to-cache }}
        cache-suffix: ${{ inputs.cache-suffix }}
