name: "terraform"
description: "Run terraform commands via the Makefile"
inputs:
  command:
    description: "Terraform command to run"
    required: true
  workspace:
    description: "Terraform workspace name"
    required: true
  account-wide:
    description: "If account-wide then specify 'account_wide'"
    required: false
    default: "non_account_wide"
  cache-suffix:
    description: "[Optional] Cache suffix (e.g. 'base')"
    required: false
    default: ""
  restore-from-cache:
    description: "[Optional] restore from cache?"
    required: false
    default: "true"
  save-to-cache:
    description: "[Optional] save to cache?"
    required: false
    default: "false"
  parameter-deploy:
    description: "If account wide parameter deploy then specify 'parameter_deploy'"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/make/
      with:
        command: terraform--${{ inputs.command }} TERRAFORM_WORKSPACE="${{ inputs.workspace }}" ACCOUNT_WIDE="${{ inputs.account-wide }}" PARAMETER_DEPLOY="${{ inputs.parameter-deploy }}"
        requires-aws: true
        restore-from-cache: ${{ inputs.restore-from-cache }}
        save-to-cache: ${{ inputs.save-to-cache }}
        cache-suffix: ${{ inputs.cache-suffix }}
