# NB: This file is our own configuration format
# for the fhir-swagger-generator: it is not an OpenAPI spec!
#
# Calling the standard build routine for this project ("make build")
# will trigger the base swagger file to be updated with operations
# on the below FHIR entities.
#
# Please update the below mapping of FHIR entities on to any of the
# RESTful API "Instance Level" or "Type Level" interactions
# described in https://hl7.org/fhir/r4b/http.html

Device: [create, read, search]
Product: [create, read]
