import pytest
from domain.core.load_questionnaire import render_questionnaire
from domain.core.questionnaire import Question
from domain.core.questionnaire_validation_custom_rules import empty_str, url


@pytest.mark.parametrize(
    ["name", "version"],
    [["spine_endpoint", 1]],
)
def test_spine_endpoint_questionnaire_v1(name: str, version: int):
    spine_endpoint_questionnaire_v1 = render_questionnaire(
        questionnaire_name=name, questionnaire_version=version
    )

    assert spine_endpoint_questionnaire_v1 is not None
    assert spine_endpoint_questionnaire_v1.name == name
    assert spine_endpoint_questionnaire_v1.version == version

    EXPECTED_QUESTIONS = [
        Question(
            name="nhs_mhs_end_point",
            human_readable_name="This is the address",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules={url},
            choices=set(),
        ),
        Question(
            name="unique_identifier",
            human_readable_name="This is the ASID",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_id_code",
            human_readable_name="This is the Managing Organization",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_party_key",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_cpa_id",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_actor",
            human_readable_name="This is the Reliability Configuration Actor",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices={
                "urn:oasis:names:tc:ebxml-msg:actor:topartymsh",
                "urn:oasis:names:tc:ebxml-msg:actor:nextmsh",
            },
        ),
        Question(
            name="nhs_mhs_sync_reply_mode",
            human_readable_name="This is the Reliability Configuration Reply Mode",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices={"MSHSIGNALSONLY", "NEVER", "NONE", "SIGNALSANDRESPONSE"},
        ),
        Question(
            name="nhs_mhs_retry_interval",
            human_readable_name="This is the Reliability Configuration Retry Interval",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_retries",
            human_readable_name="This is the Reliability Configuration Retries",
            answer_types={str, int},
            mandatory=False,
            multiple=False,
            validation_rules={empty_str},
            choices=set(),
        ),
        Question(
            name="nhs_mhs_persist_duration",
            human_readable_name="This is the Reliability Configuration Persist Duration",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_duplicate_elimination",
            human_readable_name="This is the Reliability Configuration Duplication Elimination",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices={"ALWAYS", "NEVER"},
        ),
        Question(
            name="nhs_mhs_ack_requested",
            human_readable_name="This is the Reliability Configuration Ack Requested",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices={"ALWAYS", "NEVER"},
        ),
        Question(
            name="nhs_mhs_svc_ia",
            human_readable_name="This is the interaction ID",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="object_class",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices={"nhsmhs"},
        ),
        Question(
            name="nhs_approver_urp",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_contract_property_template_key",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_date_approved",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_date_dns_approved",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_date_requested",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_dns_approver",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_ep_interaction_type",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices={"FHIR", "HL7", "EBXML", "N/A", "MSHSIGNALSONLY"},
        ),
        Question(
            name="nhs_mhs_fqdn",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_in",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_ip_address",
            human_readable_name="",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_is_authenticated",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices={"NONE", "TRANSIENT", "PERSISTENT"},
        ),
        Question(
            name="nhs_mhs_sn",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_product_key",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_product_name",
            human_readable_name="",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_product_version",
            human_readable_name="",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_requestor_urp",
            human_readable_name="",
            answer_types={str},
            mandatory=True,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
        Question(
            name="nhs_mhs_service_description",
            human_readable_name="",
            answer_types={str},
            mandatory=False,
            multiple=False,
            validation_rules=set(),
            choices=set(),
        ),
    ]

    assert len(EXPECTED_QUESTIONS) == len(spine_endpoint_questionnaire_v1.questions)

    for expected_question in EXPECTED_QUESTIONS:
        actual_question = spine_endpoint_questionnaire_v1.questions[
            expected_question.name
        ]

        assert expected_question == actual_question
