#!/bin/bash

PROFILE_PREFIX="nhse-cpm"
AWS_REGION_NAME="eu-west-2"
VERSION="v1.0.0"
MGMT_ACCOUNT_ID_LOCATION="${PROFILE_PREFIX}--mgmt--mgmt-account-id-${VERSION}"
PROD_ACCOUNT_ID_LOCATION="${PROFILE_PREFIX}--mgmt--prod-account-id-${VERSION}"
REF_ACCOUNT_ID_LOCATION="${PROFILE_PREFIX}--mgmt--ref-account-id-${VERSION}"
INT_ACCOUNT_ID_LOCATION="${PROFILE_PREFIX}--mgmt--int-account-id-${VERSION}"
QA_ACCOUNT_ID_LOCATION="${PROFILE_PREFIX}--mgmt--qa-account-id-${VERSION}"
DEV_ACCOUNT_ID_LOCATION="${PROFILE_PREFIX}--mgmt--dev-account-id-${VERSION}"
