name: "pytest Tests"
description: "Run pytest tests, with a rerun of failed tests"
inputs:
  test-type:
    description: "Test to run (unit, integration, smoke)"
    required: true
  requires-aws:
    description: "[Optional] Assume the CI AWS Role during this operation?"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/make/
      with:
        command: test--${{ inputs.test-type }}
        requires-aws: ${{ inputs.requires-aws }}

    - uses: ./.github/actions/make/
      with:
        command: test--${{ inputs.test-type }}--rerun PYTEST_FLAGS="--suppress-no-test-exit-code"
        requires-aws: ${{ inputs.requires-aws }}
        restore-from-cache: "false"
