name: "Synchronise cache"
description: "Synchronise cache"
inputs:
  cache-suffix:
    description: "[Optional] Cache prefix (e.g. 'base')"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Create cache
      uses: actions/cache@v3
      with:
        path: |
          .venv
          .timestamp
          **/dist/*zip
        key: ${{ env.GITHUB_SHA_SHORT }}-${{ inputs.cache-suffix == '' && 'head' || inputs.cache-suffix }}
