name: "Synchronise cache"
description: "Synchronise cache"
inputs:
  cache-suffix:
    description: "[Optional] Cache prefix (e.g. 'base')"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Get current date
      shell: bash
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%M:%S')" >> $GITHUB_OUTPUT
    - name: Create cache
      uses: actions/cache@v3
      with:
        path: |
          .venv
          .timestamp
          **/dist/*zip
          **/tfplan
        key: ${{ env.GITHUB_SHA_SHORT }}-${{ inputs.cache-suffix == '' && 'head' || inputs.cache-suffix }}-${{ steps.date.outputs.date }}
        restore-keys: |
          ${{ env.GITHUB_SHA_SHORT }}-${{ inputs.cache-suffix == '' && 'head' || inputs.cache-suffix }}
