name: "Deploy: Account Wide - Nonprod"

on:
  workflow_dispatch:
    inputs:
      account:
        description: Account to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - int
          - ref
          - mgmt
jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: ${{ inputs.account }}
      workspace: ${{ inputs.account }}
      scope: "per_account/${{ inputs.account }}"
    secrets: inherit # pragma: allowlist secret

run-name: Deploying account wide to nonprod workspace - ${{ inputs.account }}
