name: "Deploy: Account Wide Resources - Nonprod"

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: Account to deploy to
        required: true
        default: dev
        type: choice
        options:
          - dev
          - ref
          - int
jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace: ${{ inputs.workspace }}
      account-wide: account_wide
    secrets: inherit # pragma: allowlist secret
