name: "Deploy: Parameters - Nonprod"

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: Workspace to deploy to
        required: true
        default: dev
        type: choice
        options:
          - dev
          - ref
          - int

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace: ${{ inputs.workspace }}
      parameter-deploy: "parameter_deploy"
      account-wide: "account_wide"
    secrets: inherit # pragma: allowlist secret
