name: "Deploy: EPR Workspace - Production"
run-name: Deploying EPR to prod workspace - prod

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: prod
      workspace: prod
      scope: per_workspace/cpm_epr
    secrets: inherit # pragma: allowlist secret
