name: "Deploy: Workspace - Nonprod"

on:
  workflow_dispatch:
    inputs:
      account:
        description: Account to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - int
          - ref
      sandbox:
        description: Do you want to deploy the sandbox version?
        type: boolean
        default: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: ${{ inputs.account }}
      workspace: ${{ inputs.account }}${{ inputs.sandbox == true && '-sandbox' || '' }}
      scope: "per_workspace"
    secrets: inherit # pragma: allowlist secret

run-name: "Deploying to nonprod workspace - ${{ inputs.account }} sandbox:${{ inputs.sandbox }}"
