name: "Deploy: Workspace - Production"

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: prod
      workspace: prod
      scope: per_workspace
    secrets: inherit # pragma: allowlist secret
