name: "Deploy: Parameters - Backups"

on:
  workflow_dispatch:
    inputs:
      account:
        description: Account to deploy
        required: true
        default: backups

jobs:
  deploy:
    uses: ./.github/workflows/_deploy_backups.yml
    with:
      account: ${{ inputs.account }}
      workspace: ${{ inputs.account }}
      scope: "per_account/${{ inputs.account }}/parameters"
    secrets: inherit # pragma: allowlist secret

run-name: Deploying parameters to nonprod workspace - ${{ inputs.account }}
