name: "Deploy: Account Wide Resources - Production"

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace: prod
      account-wide: account_wide
    secrets: inherit # pragma: allowlist secret
