name: "Deploy: Account Wide - Production"
run-name: Deploying account wide to prod workspace - prod

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: prod
      workspace: prod
      scope: per_account/prod
    secrets: inherit # pragma: allowlist secret
