name: "Deploy: Account Wide - Production"

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: prod
      workspace: prod
      scope: per_account/prod
      run_smoke_tests: false
    secrets: inherit # pragma: allowlist secret
