name: "Deploy: Parameters - Production"

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: prod
      workspace: prod
      scope: per_account/prod/parameters
    secrets: inherit # pragma: allowlist secret
