name: "Deploy: Parameters - Nonprod"

on:
  workflow_dispatch:
    inputs:
      account:
        description: Account to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - int
          - ref

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      account: ${{ inputs.account }}
      workspace: ${{ inputs.account }}
      scope: "per_account/${{ inputs.account }}/parameters"
      run_smoke_testsoke_tests: false
    secrets: inherit # pragma: allowlist secret
