name: "Deploy: Parameters - Production"

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      workspace: prod
      parameter-deploy: "parameter_deploy"
      account-wide: "account_wide"
    secrets: inherit # pragma: allowlist secret
