name: Scheduled Workspace Destroy

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC).

permissions:
  id-token: write
  contents: read
  actions: write

env:
  AWS_DEFAULT_REGION: eu-west-2
  TF_CLI_ARGS: -no-color

jobs:
  destroy_expired_workspace:
    runs-on: [self-hosted, ci]
    steps:
      - uses: ./.github/actions/make/
        with:
          command: automated--destroy TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          requires-aws: true
