name: Scheduled Workspace Destroy

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC).
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write

env:
  AWS_DEFAULT_REGION: eu-west-2
  TF_CLI_ARGS: -no-color
  CI_ROLE_NAME: ${{ secrets.CI_ROLE_NAME }}

jobs:
  parse-secrets:
    runs-on: [self-hosted, ci]
    steps:
      - id: parse-secrets
        run: |
          echo "::add-mask::${{ secrets.CI_ROLE_NAME }}"

  destroy_expired_workspace:
    runs-on: [self-hosted, ci]
    needs: [parse-secrets]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: ./.github/actions/make/
        with:
          command: automated--destroy TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          requires-aws: true
