name: "Workflow: Forbid feature branch merge"

on: pull_request

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  workflow--check--release-branch-name:
    runs-on: [self-hosted, ci]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: ./.github/actions/make/
        with:
          command: workflow--check--release-branch-name
