name: "On PR Close"

permissions:
  id-token: write
  contents: read
  actions: write

env:
  TF_CLI_ARGS: -no-color
  CI_ROLE_NAME: ${{ secrets.CI_ROLE_NAME }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  BRANCH_GITHUB_SHA_SHORT: $(echo ${{ github.event.pull_request.head.sha }} | cut -c 1-7)

on:
  pull_request:
    types: [closed]

jobs:
  parse-secrets:
    runs-on: [self-hosted, ci]
    steps:
      - id: parse-secrets
        run: |
          echo "::add-mask::${{ secrets.CI_ROLE_NAME }}"

  build-base:
    runs-on: [self-hosted, ci]
    needs: [parse-secrets]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: build
          save-to-cache: "true"
          restore-from-cache: "false"

  destroy-test:
    runs-on: [self-hosted, ci]
    needs: [parse-secrets, build-base]
    steps:
      - name: Branch to destroy
        run: |
          echo "This will destroy all workspaces associated with branch name: ${{ github.head_ref }}"
