name: Pull Request

on: pull_request

permissions:
  id-token: write
  contents: read
  actions: write

env:
  BASE_CACHE_SUFFIX: base
  AWS_DEFAULT_REGION: eu-west-2
  BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  TF_CLI_ARGS: -no-color

jobs:
  create-timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.create_timestamp.outputs.timestamp }}
    steps:
      - id: create_timestamp
        run: |
          echo "timestamp=$(date -d "+3 days" "+%Y.%m.%d.%H.%M.%S")" >> $GITHUB_OUTPUT

  workflow--check--branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: workflow--check--branch-name

  build-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      ##### REMOVE THE FOLLOWING AFTER RUNNERS SET UP ######
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - uses: ./.github/actions/make/
        with:
          command: poetry--install
      ######################################################
      - uses: ./.github/actions/make/
        with:
          command: build--python # CHANGE TO "build" once runners are set up

  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}
      ##### REMOVE THE FOLLOWING AFTER RUNNERS SET UP ######
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - uses: ./.github/actions/make/
        with:
          command: poetry--install
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}
      ######################################################
      - uses: ./.github/actions/make/
        with:
          command: build--python # CHANGE TO "build" once runners are set up
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}

  workflow--codebase-checks:
    runs-on: ubuntu-latest
    needs: [workflow--check--branch-name, build-head, build-base]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      ##### REMOVE THE FOLLOWING AFTER RUNNERS SET UP ######
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      - uses: ./.github/actions/make/
        with:
          command: poetry--install
      ######################################################
      - uses: ./.github/actions/make/
        with:
          command: workflow--codebase-checks

  test--unit:
    needs: [build-head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      ##### REMOVE THE FOLLOWING AFTER RUNNERS SET UP ######
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      ######################################################
      - uses: ./.github/actions/pytest-with-rerun/
        with:
          test-type: unit

  test--feature--local:
    needs: [build-head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      ##### REMOVE THE FOLLOWING AFTER RUNNERS SET UP ######
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      ######################################################
      - uses: ./.github/actions/make/
        with:
          command: test--feature--local

  helpers--truststore-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: helpers--truststore-pull WORKSPACE=ref

  terraform-base-build:
    needs: [create-timestamp, build-base, helpers--truststore-pull]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: terraform--plan WORKSPACE="ci-${{ needs.create-timestamp.outputs.timestamp }}" TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}
          aws-role-to-assume: ${{ secrets.CI_ROLE_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: terraform--apply WORKSPACE="ci-${{ needs.create-timestamp.outputs.timestamp }}" TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}
          aws-role-to-assume: ${{ secrets.CI_ROLE_NAME }}

  terraform-head-build:
    needs:
      [
        create-timestamp,
        build-head,
        workflow--codebase-checks,
        test--unit,
        test--feature--local,
        helpers--truststore-pull,
        terraform-base-build,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: terraform--plan WORKSPACE="ci-${{ needs.create-timestamp.outputs.timestamp }}" TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          aws-role-to-assume: ${{ secrets.CI_ROLE_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: terraform--apply WORKSPACE="ci-${{ needs.create-timestamp.outputs.timestamp }}" TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          aws-role-to-assume: ${{ secrets.CI_ROLE_NAME }}

  test--integration:
    needs:
      [
        build-head,
        workflow--codebase-checks,
        test--unit,
        test--feature--local,
        terraform-head-build,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      ##### REMOVE THE FOLLOWING AFTER RUNNERS SET UP ######
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.6.1
      ######################################################
      - uses: ./.github/actions/pytest-with-rerun/
        with:
          test-type: integration
          aws-role-to-assume: ${{ secrets.CI_ROLE_NAME }}
