name: "Workflow: Pull Request"

on: pull_request

permissions:
  id-token: write
  contents: read
  actions: write

env:
  BASE_CACHE_SUFFIX: base
  BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
  CI_ROLE_NAME: ${{ secrets.CI_ROLE_NAME }}
  RUNNING_IN_CI: 1
  BRANCH_GITHUB_SHA_SHORT: $(echo ${{ github.event.pull_request.head.sha }} | cut -c 1-7)
  TF_CLI_ARGS: -no-color

jobs:
  workflow--check--branch-name:
    runs-on: [self-hosted, ci]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: workflow--check--branch-name

  parse-secrets:
    runs-on: [self-hosted, ci]
    needs: [workflow--check--branch-name]
    steps:
      - id: parse-secrets
        run: |
          echo "::add-mask::${{ secrets.CI_ROLE_NAME }}"

  create-workspace-name:
    runs-on: [self-hosted, ci]
    needs: [workflow--check--branch-name]
    outputs:
      workspace: ${{ steps.create_workspace_name.outputs.workspace }}
    steps:
      - id: create_workspace_name
        # will create a workspace in the format ci-PI-70-b25lkjd or for release branches rel-2023-10-30-lskjdld
        run: |
          if [[ ${{ env.BRANCH_NAME }} == *"release/"* ]]; then
            echo "workspace=rel-$(echo ${{ env.BRANCH_NAME }} | sed 's/release\///')-${{ env.BRANCH_GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
          else
            echo "workspace=ci-$(echo ${{ env.BRANCH_NAME }} | sed -n 's/.*\/\([^-]*\)-\([^-]*\).*/\1-\2/p')-${{ env.BRANCH_GITHUB_SHA_SHORT }}" >> $GITHUB_OUTPUT
          fi

  build-head:
    runs-on: [self-hosted, ci]
    needs: [parse-secrets]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: build

  build-base:
    runs-on: [self-hosted, ci]
    needs: [workflow--check--branch-name]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: build
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}

  workflow--codebase-checks:
    runs-on: [self-hosted, ci]
    needs: [build-head]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: workflow--codebase-checks

  test--unit:
    needs: [build-head]
    runs-on: [self-hosted, ci]
    strategy:
      matrix:
        test-type: [unit, slow]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/pytest-with-rerun/
        with:
          test-type: ${{ matrix.test-type }}

  test--feature--local:
    needs: [build-head]
    runs-on: [self-hosted, ci]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: test--feature--local

  helpers--truststore-pull:
    runs-on: [self-hosted, ci]
    needs: [workflow--check--branch-name]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/make/
        with:
          command: helpers--truststore-pull WORKSPACE=ref

  terraform-base-build:
    needs:
      [
        create-workspace-name,
        build-base,
        helpers--truststore-pull,
        parse-secrets,
      ]
    runs-on: [self-hosted, ci]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH_NAME }}
      - uses: ./.github/actions/terraform/
        with:
          command: plan
          workspace: ${{ needs.create-workspace-name.outputs.workspace }}
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}
      - uses: ./.github/actions/terraform/
        with:
          command: apply
          workspace: ${{ needs.create-workspace-name.outputs.workspace }}
          cache-suffix: ${{ env.BASE_CACHE_SUFFIX }}

  terraform-head-build:
    needs:
      [
        create-workspace-name,
        build-head,
        workflow--codebase-checks,
        test--unit,
        test--feature--local,
        helpers--truststore-pull,
        parse-secrets,
        terraform-base-build,
      ]
    runs-on: [self-hosted, ci]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/terraform/
        with:
          command: plan
          workspace: ${{ needs.create-workspace-name.outputs.workspace }}
      - uses: ./.github/actions/terraform/
        with:
          command: apply
          workspace: ${{ needs.create-workspace-name.outputs.workspace }}

  test--integration:
    needs:
      [
        build-head,
        workflow--codebase-checks,
        test--unit,
        test--feature--local,
        terraform-head-build,
      ]
    runs-on: [self-hosted, ci]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
      - uses: ./.github/actions/pytest-with-rerun/
        with:
          test-type: integration
          requires-aws: true

  destroy-redundant-workspaces:
    runs-on: [self-hosted, ci]
    needs: [build-head]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          fetch-depth: 0
      - uses: ./.github/actions/make/
        with:
          command: destroy--redundant-workspaces BRANCH_NAME=origin/${{ env.BRANCH_NAME }} DESTROY_ALL_COMMITS_ON_BRANCH=false KILL_ALL=false CURRENT_COMMIT="${{ env.BRANCH_GITHUB_SHA_SHORT }}" TF_CLI_ARGS=${{ env.TF_CLI_ARGS }}
          requires-aws: true
